[project]
name = 'jupyter_code_server'
version = '1.1'
description = 'Running the Visual Studio Code Web IDE inside the Jupyter environment'
readme = 'README.md'
requires-python = ">=3.8"
classifiers = [
"Programming Language :: Python :: 3.8"
]
dependencies = [
  'jupyter-server-proxy >= 4.1.2',
]

[tool.setuptools.packages.find]
where = ["binder/src"]

[project.entry-points."jupyter_serverproxy_servers"]
vscode = "jupyter_code_server:setup_code_server"
